---
# yamllint disable rule:key-ordering
stages:
- checks
- build

image:
  name: danielfdickinson/gitlab-debian-ansible-pre-commit:0.2.4

workflow:
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: $CI_COMMIT_TAG
  - if: $CI_COMMIT_REF_PROTECTED

# before_script:
# - echo here

checks_a:
  stage: checks
  script:
  - chmod 0700 .
  - >
      pre-commit install --install-hooks
  - >
      pre-commit run --all-files
...
