---
# yamllint disable rule:key-ordering
stages:
- checks
- build

image:
  name: danielfdickinson/gitlab-debian-ansible-pre-commit:0.2.2

include:
- template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

# before_script:
# - echo here

checks_a:
  stage: checks
  script:
  - chmod 0700 .
  - >
      pre-commit install --install-hooks
  - >
      pre-commit run --all-files
...
